### ISSUE TITLE
Open issues for triton-inference-server (round 2)

### ISSUE THREAD

**Issue by kpedro88** [hls-fpga-machine-learning/SonicCMS#17]
Tracking the second round of issues submitted to [triton-inference-server](https://github.com/triton-inference-server/server):
- [ ] https://github.com/triton-inference-server/server/issues/2018: Control number of threads used by CPU server
- [x] https://github.com/triton-inference-server/server/issues/2019: Stricter model versioning
- [ ] https://github.com/triton-inference-server/server/issues/2020: Ability to disable or redirect cout/cerr
- [x] https://github.com/triton-inference-server/server/issues/2021: Support input/output compression
- [x] https://github.com/triton-inference-server/server/issues/2158: Ragged batching support for ML backends
- [ ] https://github.com/triton-inference-server/server/issues/2159: Support different network protocols
- [x] https://github.com/triton-inference-server/server/issues/3141: CMake problems for client library in v2.11.0

**Comment by kpedro88** [comment]
Model checksum support has been added: https://github.com/triton-inference-server/checksum_repository_agent

**Comment by kpedro88** [comment]
I/O compression is available and implemented in CMSSW in https://github.com/cms-sw/cmssw/pull/34508
